application: brandaproject
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img
- url: /static
  static_dir: static
- url: /test.*
  script: gaeunit.py
- url: /.*
  script: frontend/frontend.py

skip_files:
- ^(.*/)?\.tmproj.*